AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Immigration AI Agent Backend - With Document Processing

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 512
    Environment:
      Variables:
        USERS_TABLE: !Ref UsersTable
        POLICIES_TABLE: !Ref PoliciesTable
        DOCUMENTS_TABLE: !Ref DocumentsTable
        DOCUMENTS_BUCKET: !Sub 'immigration-ai-documents-${AWS::AccountId}'
        ENVIRONMENT: dev

Resources:
  # ============================================
  # DYNAMODB TABLES
  # ============================================
  
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: immigration-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PoliciesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: immigration-policies
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: policy_id
          AttributeType: S
        - AttributeName: published_date
          AttributeType: S
      KeySchema:
        - AttributeName: policy_id
          KeyType: HASH
        - AttributeName: published_date
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  DocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: immigration-documents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: document_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: document_id
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # ============================================
  # S3 BUCKET FOR DOCUMENTS - NO NOTIFICATION YET
  # ============================================
  
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'immigration-ai-documents-${AWS::AccountId}'
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE]
            AllowedHeaders: ['*']
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldDocuments
            Status: Enabled
            ExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # ============================================
  # AUTH LAMBDA FUNCTIONS
  # ============================================
  
  SignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: immigration-ai-signup
      CodeUri: lambdas/auth/
      Handler: signup.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Signup:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /api/auth/signup
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: immigration-ai-login
      CodeUri: lambdas/auth/
      Handler: login.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /api/auth/login
            Method: post

  # ============================================
  # POLICY LAMBDA FUNCTIONS
  # ============================================
  
  GetPoliciesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: immigration-ai-get-policies
      CodeUri: lambdas/policies/
      Handler: get_policies.lambda_handler
      Layers:
        - !Ref SharedLibLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PoliciesTable
      Events:
        GetPolicies:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /api/policies
            Method: get

  ScrapePoliciesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: immigration-ai-scrape-policies
      CodeUri: lambdas/policies/
      Handler: scrape_policies.lambda_handler
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          GEMINI_API_KEY: !Sub '{{resolve:secretsmanager:immigration-ai/gemini-key}}'
      Layers:
        - !Ref SharedLibLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PoliciesTable
        - Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: 
              - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:immigration-ai/gemini-key*'
      Events:
        ManualInvoke:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /api/policies/scrape
            Method: post

  # ============================================
  # DOCUMENT PROCESSING LAMBDA FUNCTIONS
  # ============================================
  
  UploadDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: immigration-ai-upload-document
      CodeUri: lambdas/documents/
      Handler: upload.lambda_handler
      Timeout: 30
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DocumentsBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentsTable
      Events:
        Upload:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /api/documents/upload
            Method: post

  ProcessDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: immigration-ai-process-document
      CodeUri: lambdas/documents/
      Handler: process.lambda_handler
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          GEMINI_API_KEY: !Sub '{{resolve:secretsmanager:immigration-ai/gemini-key}}'
      Layers:
        - !Ref SharedLibLayer
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentsBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentsTable
        - Statement:
          - Effect: Allow
            Action:
              - textract:AnalyzeDocument
              - textract:DetectDocumentText
            Resource: '*'
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: 
              - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:immigration-ai/gemini-key*'

  ProcessDocumentInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProcessDocumentFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt DocumentsBucket.Arn

  GetDocumentStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: immigration-ai-get-document-status
      CodeUri: lambdas/documents/
      Handler: get_status.lambda_handler
      Timeout: 10
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DocumentsTable
      Events:
        GetStatus:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /api/documents/{document_id}/status
            Method: get

  GetDocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: immigration-ai-get-documents
      CodeUri: lambdas/documents/
      Handler: get_documents.lambda_handler
      Timeout: 10
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DocumentsTable
      Events:
        GetDocuments:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /api/documents
            Method: get

  # ============================================
  # S3 BUCKET NOTIFICATION - SEPARATE RESOURCE
  # ============================================
  
  S3BucketNotification:
    Type: Custom::S3BucketNotification
    DependsOn:
      - ProcessDocumentInvokePermission
    Properties:
      ServiceToken: !GetAtt S3NotificationFunction.Arn
      BucketName: !Ref DocumentsBucket
      LambdaFunctionArn: !GetAtt ProcessDocumentFunction.Arn

  S3NotificationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: immigration-ai-s3-notification-handler
      Runtime: python3.11
      Handler: index.handler
      Timeout: 60
      Role: !GetAtt S3NotificationFunctionRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          import cfnresponse
          
          s3 = boto3.client('s3')
          
          def handler(event, context):
              print(f"Event: {json.dumps(event)}")
              
              try:
                  request_type = event['RequestType']
                  properties = event['ResourceProperties']
                  bucket_name = properties['BucketName']
                  lambda_arn = properties['LambdaFunctionArn']
                  
                  if request_type in ['Create', 'Update']:
                      # Add S3 notification
                      s3.put_bucket_notification_configuration(
                          Bucket=bucket_name,
                          NotificationConfiguration={
                              'LambdaFunctionConfigurations': [
                                  {
                                      'LambdaFunctionArn': lambda_arn,
                                      'Events': ['s3:ObjectCreated:*']
                                  }
                              ]
                          }
                      )
                      print(f"✓ S3 notification configured for {bucket_name}")
                  
                  elif request_type == 'Delete':
                      # Remove notification on stack delete
                      s3.put_bucket_notification_configuration(
                          Bucket=bucket_name,
                          NotificationConfiguration={}
                      )
                      print(f"✓ S3 notification removed for {bucket_name}")
                  
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              
              except Exception as e:
                  print(f"ERROR: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Error': str(e)})

  S3NotificationFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: immigration-ai-s3-notification-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3NotificationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutBucketNotification
                  - s3:GetBucketNotification
                Resource: !GetAtt DocumentsBucket.Arn

  # ============================================
  # LAMBDA LAYER
  # ============================================
  
  SharedLibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: immigration-ai-shared-lib
      ContentUri: lambdas/lib/
      CompatibleRuntimes:
        - python3.11

  # ============================================
  # API GATEWAY - CORS FIX APPLIED
  # ============================================
  
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: immigration-ai-api
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Requested-With,Accept,x-user-email,x-auth-token,X-User-Email,X-Auth-Token'"
        AllowOrigin: "'*'"
        AllowCredentials: false
        MaxAge: "'600'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Requested-With,Accept,x-user-email,x-auth-token,X-User-Email,X-Auth-Token'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Requested-With,Accept,x-user-email,x-auth-token,X-User-Email,X-Auth-Token'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"

# ============================================
# OUTPUTS
# ============================================

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  PoliciesTableName:
    Description: Policies DynamoDB table name
    Value: !Ref PoliciesTable
  
  DocumentsTableName:
    Description: Documents DynamoDB table name
    Value: !Ref DocumentsTable
  
  DocumentsBucketName:
    Description: Documents S3 bucket name
    Value: !Ref DocumentsBucket
  
  ProcessDocumentFunctionArn:
    Description: Process Document Lambda ARN
    Value: !GetAtt ProcessDocumentFunction.Arn